/* tslint:disable */
/* eslint-disable */
/**
 * SpringBoot3.4.x-init
 * Virosa-Plus
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: 2156722358@qq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

